#!/bin/sh -e


log() {
	printf "[INFO] %s\n" "$@"
}

logerr() {
	printf "[ERR] %s\n" "$@"
}

# Create virtual microphone
create() {
	log "Creating virtual microphone device."

	mkdir -p /tmp/dumic
	
	pactl load-module module-pipe-source source_name="dumic_in" file=/tmp/dumic/in channels=1 rate=44100 format=s16le > /dev/null 2>&1
	pactl load-module module-loopback source="$(pactl list short sources | grep "dumic_in" | cut -f1)" latency_msec=8 > /dev/null 2>&1

	log "Virtual microphone device has been created"
}

# Play audio files
play() {
	[ ! -d "/tmp/dumic" ] && logerr "The virtual microphone does not exist. Please run 'dumic -s' to create one."

	ffmpeg -re -i "$1" -f s16le -ar 44100 -ac 1 - > /tmp/dumic/in
}


loop() {
       while sleep 1; do
         play
       done
}


# Check for dependencies
deps_met=true
[ ! "$(command -v ffmpeg)" ] && logerr "The dependency 'ffmpeg' is missing." && deps_met=false
[ ! "$(command -v pactl)" ] && logerr "The dependency 'pactl' is missing." && deps_met=false
[ "$deps_met" = "false" ] && exit 1

# Read arguments from CLI
case $1 in
	-p|--play)	play "$2" ;;
	-s|--start)	create ;;
        -l|--loop)      loop "$1" ;;
	*)			printf "%s\n%s\n%s\n" "Usage: dumic -[p|s] [...]" \
					   "-p, --play /path/to/audio : play audio files through virtual microphone" \
                                           "-l, --loop /path/to/audio : play audio files through virtual microphone but looped" \
					   "-s, --start               : create virtual microphone device" ;;
esac

